title: Wir für dich. Du mit uns.
description: Dokumentation der Plattform, die noch keinen Namen besitzt.
theme: just-the-docs

url: https://timelaut.github.io/wirfuerdichdumituns/

aux_links:
  Template Repository: https://github.com/timelaut/wirfuerdichdumituns
